project:
  type: website
  output-dir: docs


website:
  title: "Above Ventures"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - aboutus.qmd
      - projects.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


